<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '2371fe58591751a9b725c6706865644e' => $vendorDir . '/lichtner/fluentpdo/FluentPDO/FluentPDO.php',
);
